### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by wildandfree** [gumho/antplanner2#34]
The page is unable to load, no matter how many times I refresh it. I've also tried using different browsers and have encountered the same problem on all of them. Below is a screenshot of what it looks like. Please fix!

![untitled](https://cloud.githubusercontent.com/assets/14142907/9701454/ce6fdbe0-53de-11e5-8efb-e94c43bcde66.png)

**Comment by gumho** [comment]
Thanks for reporting this! Looks like some of the URLs changed in WebSoc and I needed to update those.
